language: python
python:
  - "3.5"
  - "3.3"
  - "2.7"
install:
  - pip install python-coveralls coverage
  - pip install -r requirements.txt
  - pip install pytest
script:  py.test
after_success:
  - coveralls --config_file .coveragerc
sudo: false